module.exports = {
  port: process.env.PORT || 3000,
  name: 'payment-gateway',
  base_url: process.env.BASE_URL || 'http://localhost:8080',
  secret: process.env.APP_SECRET || 'aidh82n3ie8h2nms9u2hwms8u2b',
  releaseStage: process.env.NODE_ENV || 'development',
  stagingUrl: process.env.STAGING_URL || 'https://staging.moneywaveapp.com',
  mwApiKey: process.env.MW_API_KEY,
  mwSecret: process.env.MW_SECRET,
  mwWalletPassword: process.env.MW_WALLET_PASSWORD,
  paystackUrl: process.env.PAYSTACK_URL || 'https://api.paystack.co',
  paystackPublicKey: process.env.PAYSTACK_PUBLIC_KEY,
  accountEmail: process.env.ACCOUNT_EMAIL,
  accountPassword: process.env.ACCOUNT_PASSWORD,
  db: {
    username: process.env.DB_USERNAME || 'root',
    password: process.env.DB_PASSWORD || 'root',
    database: process.env.DB_NAME || 'payment-gateway',
    host: process.env.DB_HOST || '127.0.0.1',
    dialect: process.env.DB_TYPE || 'mysql',
    use_env_variable: process.env.DATABASE_USE_URL,
    url: process.env.JAWSDB_URL,
    timezone: '+01:00',
    logging: false,
  },
};
